global:
  imagePullSecrets: []

nameOverride: ""

# rsyslogd
image:
  repository: rsyslog/rsyslog-collector
  tag: ""
  pullPolicy: IfNotPresent

replicas: 1
resources:
  requests:
    cpu: "250m"
    memory: "512Mi"
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 4
  targetCPUUtilizationPercentage: 75
  targetMemoryUtilizationPercentage: 75
  behavior: {}
    # scaleDown:
    #  stabilizationWindowSeconds: 300
    #  policies:
    #   - type: Pods
    #     value: 1
    #     periodSeconds: 180
    # scaleUp:
    #   stabilizationWindowSeconds: 300
    #   policies:
    #   - type: Pods
    #     value: 2
    #     periodSeconds: 60

service:
  port: 514

## Configure TLS
## Note: When TLS is enabled, you need to create a Kubernetes Secret containing the TLS certificates and specify its
## name in tls.secretName. Also, the "latest" image will be used, which is configured for TLS. Finally, the container
## port will be switched to 6514, RFC 5425. The service port will remain unchanged, so the Kubernetes Service still
## exposes the rsyslog deployment on the desired port, as specified in service.port.
## @param tls.enabled Enable TLS for rsyslog
## @param tls.secretName Name of the Kubernetes Secret containing TLS certificates
tls:
  enabled: false
  authMode: "anon"
  secretName: rsyslog-tls-secret

persistence:
  enabled: false
  # storageClass: ""
  # existingClaim: rsyslog-pvc
  accessModes:
    - ReadWriteOncePod
  size: 1Gi

## Configure logrotation as a sidecar container
## @param logrotate Add logrotation as a sidecar container
logrotate:
  enabled: false
  image:
    repository: skymatic/logrotate
    tag: latest
    pullPolicy: IfNotPresent
  resources: {}
  config:
    logfiles:
      - "*.log"
    interval: daily
    rotate: 7
    missingok: true
    notifempty: true
    copytruncate: true
    olddir: old # Directory to store rotated log files; relative to /var/log
    compress: true
    delaycompress: false 

## Configure additional sidecar containers
## @param extraSidecars Add additional sidecar containers
## e.g:
## extraSidecars:
##   - name: your-image-name
##     image: your-image
##     imagePullPolicy: Always
##     ports:
##       - name: portname
##         containerPort: 1234
##
extraSidecars: []

hostAliases: []

## Configure Pods Security Context
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-pod
## @param podSecurityContext.enabled Enabled rsyslog  pods' Security Context
## @param podSecurityContext.fsGroup Set rsyslog  pod's Security Context fsGroup
##
podSecurityContext:
  enabled: false
  fsGroup: 1000
## Configure Container Security Context
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-pod
## @param containerSecurityContext.enabled Enabled rsyslog  containers' Security Context
## @param containerSecurityContext.runAsUser Set rsyslog  containers' Security Context runAsUser
## @param containerSecurityContext.runAsNonRoot Set rsyslog  containers' Security Context runAsNonRoot
##
containerSecurityContext:
  enabled: false
  runAsUser: 1000
  runAsNonRoot: true

## Configure extra options for liveness, readiness, and startup probes
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#configure-probes
livenessProbe:
  enabled: true
  initialDelaySeconds: 20
  periodSeconds: 10
  timeoutSeconds: 1
  successThreshold: 1
  failureThreshold: 10
readinessProbe:
  enabled: true
  initialDelaySeconds: 20
  periodSeconds: 10
  timeoutSeconds: 1
  successThreshold: 1
  failureThreshold: 10
startupProbe:
  enabled: true
  initialDelaySeconds: 0
  periodSeconds: 10
  timeoutSeconds: 1
  successThreshold: 1
  failureThreshold: 30

updateStrategy:
  ## StrategyType
  ## Can be set to RollingUpdate or OnDelete
  ##
  type: RollingUpdate
